[SourceHanSansJP-Regular]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF JP
	s=3,1,0x411,Regular
	f=Source Han Sans JP
	s=Regular

[SourceHanSansJP-Bold]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF JP
	s=3,1,0x411,Bold
	f=Source Han Sans JP
	s=Bold

[SourceHanSansKR-Regular]
	f=3,1,0x412,\BCF8\ACE0\B515 KR
	s=3,1,0x412,Regular
	f=Source Han Sans KR
	s=Regular

[SourceHanSansKR-Bold]
	f=3,1,0x412,\BCF8\ACE0\B515 KR
	s=3,1,0x412,Bold
	f=Source Han Sans KR
	s=Bold

[SourceHanSansCN-Regular]
	f=3,1,0x804,\601D\6E90\9ED1\4F53 CN
	s=3,1,0x804,Regular
	f=Source Han Sans CN
	s=Regular

[SourceHanSansCN-Bold]
	f=3,1,0x804,\601D\6E90\9ED1\4F53 CN
	s=3,1,0x804,Bold
	f=Source Han Sans CN
	s=Bold

[SourceHanSansTW-Regular]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4 TW
	s=3,1,0x404,Regular
	f=Source Han Sans TW
	s=Regular

[SourceHanSansTW-Bold]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4 TW
	s=3,1,0x404,Bold
	f=Source Han Sans TW
	s=Bold
