[SourceHanSansHW-Regular]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF HW
	s=3,1,0x411,Regular
	f=Source Han Sans HW
	s=Regular

[SourceHanSansHW-Bold]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF HW
	s=3,1,0x411,Bold
	f=Source Han Sans HW
	s=Bold

[SourceHanSansHWK-Regular]
	f=3,1,0x412,\BCF8\ACE0\B515 HW
	s=3,1,0x412,Regular
	f=Source Han Sans HW K
	s=Regular

[SourceHanSansHWK-Bold]
	f=3,1,0x412,\BCF8\ACE0\B515 HW
	s=3,1,0x412,Bold
	f=Source Han Sans HW K
	s=Bold

[SourceHanSansHWSC-Regular]
	f=3,1,0x804,\601D\6E90\9ED1\4F53 HW
	s=3,1,0x804,Regular
	f=Source Han Sans HW SC
	s=Regular

[SourceHanSansHWSC-Bold]
	f=3,1,0x804,\601D\6E90\9ED1\4F53 HW
	s=3,1,0x804,Bold
	f=Source Han Sans HW SC
	s=Bold

[SourceHanSansHWTC-Regular]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4 HW
	s=3,1,0x404,Regular
	f=Source Han Sans HW TC
	s=Regular

[SourceHanSansHWTC-Bold]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4 HW
	s=3,1,0x404,Bold
	f=Source Han Sans HW TC
	s=Bold
