[SourceHanSans-Regular]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF
	s=3,1,0x411,Regular
	f=Source Han Sans
	s=Regular

[SourceHanSans-Bold]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF
	s=3,1,0x411,Bold
	f=Source Han Sans
	s=Bold

[SourceHanSansK-Regular]
	f=3,1,0x412,\BCF8\ACE0\B515
	s=3,1,0x412,Regular
	f=Source Han Sans K
	s=Regular

[SourceHanSansK-Bold]
	f=3,1,0x412,\BCF8\ACE0\B515
	s=3,1,0x412,Bold
	f=Source Han Sans K
	s=Bold

[SourceHanSansSC-Regular]
	f=3,1,0x804,\601D\6E90\9ED1\4F53
	s=3,1,0x804,Regular
	f=Source Han Sans SC
	s=Regular

[SourceHanSansSC-Bold]
	f=3,1,0x804,\601D\6E90\9ED1\4F53
	s=3,1,0x804,Bold
	f=Source Han Sans SC
	s=Bold

[SourceHanSansTC-Regular]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4
	s=3,1,0x404,Regular
	f=Source Han Sans TC
	s=Regular

[SourceHanSansTC-Bold]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4
	s=3,1,0x404,Bold
	f=Source Han Sans TC
	s=Bold
