FontName                   (SourceHanSans-Bold)
FullName                   (Source Han Sans Bold)
FamilyName                 (Source Han Sans)
Weight                     (Bold)
version                    (1.004)
Registry                   (Adobe)
Ordering                   (Identity)
Supplement                 0
XUID                       [1 11 9274279]
Layout                     (AI0-SourceHanSans)
FSType                     0
isFixedPitch               false
UnderlinePosition          -150
AdobeCopyright             (Copyright 2014, 2015 Adobe Systems Incorporated (http://www.adobe.com/), with Reserved Font Name 'Source'.)
Trademark                  (Source is a trademark of Adobe Systems Incorporated in the United States and/or other countries.)
Serif                      false
IsBoldStyle                true
IsItalicStyle              false
PreferOS/2TypoMetrics      false
IsOS/2WidthWeigthSlopeOnly false
IsOS/2OBLIQUE              false
UseOldNameID4              false
LicenseCode                ADOBE
